org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC
org.gradle.java.home=/home/sunny/.gradle/jdks/eclipse_adoptium-17-amd64-linux.2
org.gradle.workers.max=2
org.gradle.caching=true
org.gradle.parallel=false
android.useAndroidX=true
android.enableJetifier=false
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
